// Copyright 2025 JesusTouchMe

#ifndef JESUSASM_FRAMEWORK_INCLUDE_JESUSASM_ATTRIBUTE_H
#define JESUSASM_FRAMEWORK_INCLUDE_JESUSASM_ATTRIBUTE_H 1

#include "moduleweb/builder/attribute_builder.h"

#include <stdexcept>
#include <string>

namespace JesusASM {
    /**
     * Represents a nonstandard attribute that wouldn't be auto generated by anything
     */
    class Attribute {
    public:
        Attribute(std::string_view name, const void* info, u32 size);

        inline Attribute(std::string_view name, std::string_view info) : Attribute(name, info.data(), info.length()) {}

        ~Attribute();

        [[nodiscard]] std::string_view getName() const;
        [[nodiscard]] const u8* getInfo() const;
        [[nodiscard]] u32 getSize() const;

        template<class T>
        void emit(moduleweb::AttributeBuilder<T>& builder);

    private:
        std::string mName;
        u8* mInfo;
        u32 mSize;
    };

    template<class T>
    void Attribute::emit(moduleweb::AttributeBuilder<T>& builder) {
        if (mName.empty()) {
            throw std::runtime_error("Attribute name is empty");
        }

        builder
            .name(mName)
            .info(mInfo, mSize)
            .build();
    }
}

#endif // JESUSASM_FRAMEWORK_INCLUDE_JESUSASM_ATTRIBUTE_H
